#!/usr/bin/env python3
"""Small, dependency-free automation helpers for the Markdown Brain workspace."""

from __future__ import annotations

import argparse
import ast
import os
import re
import sys
from collections import Counter, defaultdict
from collections.abc import Iterable, Sequence
from dataclasses import dataclass
from datetime import date
from pathlib import Path
from typing import Any
from urllib.parse import unquote, urlsplit


GENERATED_MARKER = "<!-- generated by Tools/brain.py; do not edit -->"
INDEX_NAME = "INDEX.md"
LOG_NAME = "LOG.md"
BRAIN_DIRECTORY = "Brain"
CORPUS_DIRECTORIES = (BRAIN_DIRECTORY, "Projects")
EXCLUDED_CORPUS_NAMES = {INDEX_NAME, LOG_NAME, ".gitkeep"}
ACTIVE_SESSION_STATUSES = {"active", "open", "in-progress", "in_progress", "exploring"}
MAX_OPERATION_LENGTH = 40
MAX_TITLE_LENGTH = 160
MAX_NOTE_LENGTH = 240
EMPTY_VALUES = {
    "",
    "[]",
    "{}",
    "none",
    "null",
    "n/a",
    "na",
    "unknown",
    "todo",
    "tbd",
    "not specified",
    "not yet established",
}


@dataclass(frozen=True)
class FrontMatter:
    metadata: dict[str, Any]
    body: str
    has_frontmatter: bool = False
    error: str | None = None
    error_line: int | None = None
    body_start_line: int = 1


@dataclass(frozen=True)
class IndexEntry:
    area: str
    document_type: str
    title: str
    status: str
    summary: str
    relative_path: str


@dataclass(frozen=True)
class LintIssue:
    severity: str
    path: Path
    line: int
    message: str


def workspace_root() -> Path:
    """Locate the workspace root from Tools/brain.py."""
    return Path(__file__).resolve().parent.parent


def read_utf8(path: Path) -> str:
    """Read UTF-8 text while tolerating an optional UTF-8 BOM."""
    return path.read_text(encoding="utf-8-sig")


def _strip_yaml_comment(value: str) -> str:
    quote: str | None = None
    escaped = False
    for index, character in enumerate(value):
        if escaped:
            escaped = False
            continue
        if character == "\\" and quote == '"':
            escaped = True
            continue
        if character in {"'", '"'}:
            if quote is None:
                quote = character
            elif quote == character:
                quote = None
            continue
        if character == "#" and quote is None and (index == 0 or value[index - 1].isspace()):
            return value[:index].rstrip()
    return value.rstrip()


def _split_inline_list(value: str) -> tuple[list[Any], str | None]:
    inner = value[1:-1].strip()
    if not inner:
        return [], None

    items: list[str] = []
    current: list[str] = []
    quote: str | None = None
    escaped = False
    for character in inner:
        if escaped:
            current.append(character)
            escaped = False
            continue
        if character == "\\" and quote == '"':
            current.append(character)
            escaped = True
            continue
        if character in {"'", '"'}:
            current.append(character)
            if quote is None:
                quote = character
            elif quote == character:
                quote = None
            continue
        if character == "," and quote is None:
            items.append("".join(current).strip())
            current = []
        else:
            current.append(character)
    if quote is not None:
        return [], "unterminated quoted value in inline list"
    items.append("".join(current).strip())
    return [_parse_scalar(item)[0] for item in items], None


def _parse_scalar(raw_value: str) -> tuple[Any, str | None]:
    value = _strip_yaml_comment(raw_value).strip()
    if not value:
        return None, None
    if value.startswith("["):
        if not value.endswith("]"):
            return None, "unterminated inline list"
        return _split_inline_list(value)
    if value[0] in {"'", '"'}:
        if len(value) < 2 or value[-1] != value[0]:
            return None, "unterminated quoted value"
        try:
            return ast.literal_eval(value), None
        except (SyntaxError, ValueError):
            return None, "malformed quoted value"
    lowered = value.casefold()
    if lowered in {"null", "~"}:
        return None, None
    if lowered in {"true", "false"}:
        return lowered == "true", None
    return value, None


def parse_frontmatter(text: str) -> FrontMatter:
    """Parse the simple YAML subset used by the workspace templates.

    Top-level scalar fields, inline lists, and indented block lists are
    supported. Nested content is accepted as an opaque continuation so valid
    legacy YAML is not rejected merely because PyYAML is intentionally absent.
    """
    text = text.lstrip("\ufeff")
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return FrontMatter(metadata={}, body=text)

    closing_index: int | None = None
    for index in range(1, len(lines)):
        if lines[index].strip() == "---":
            closing_index = index
            break
    if closing_index is None:
        return FrontMatter(
            metadata={},
            body="",
            has_frontmatter=True,
            error="unterminated YAML frontmatter",
            error_line=1,
            body_start_line=len(lines) + 1,
        )

    metadata: dict[str, Any] = {}
    current_key: str | None = None
    for index in range(1, closing_index):
        line = lines[index]
        line_number = index + 1
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if "\t" in line[: len(line) - len(line.lstrip())]:
            return FrontMatter(
                metadata=metadata,
                body="\n".join(lines[closing_index + 1 :]),
                has_frontmatter=True,
                error="tabs are not allowed for YAML indentation",
                error_line=line_number,
                body_start_line=closing_index + 2,
            )
        if line[0].isspace():
            if current_key is None:
                return FrontMatter(
                    metadata=metadata,
                    body="\n".join(lines[closing_index + 1 :]),
                    has_frontmatter=True,
                    error="unexpected indentation in YAML frontmatter",
                    error_line=line_number,
                    body_start_line=closing_index + 2,
                )
            if stripped.startswith("-"):
                item_text = stripped[1:].strip()
                parsed, error = _parse_scalar(item_text)
                if error:
                    return FrontMatter(
                        metadata=metadata,
                        body="\n".join(lines[closing_index + 1 :]),
                        has_frontmatter=True,
                        error=error,
                        error_line=line_number,
                        body_start_line=closing_index + 2,
                    )
                previous = metadata.get(current_key)
                if previous is None:
                    metadata[current_key] = []
                    previous = metadata[current_key]
                if not isinstance(previous, list):
                    return FrontMatter(
                        metadata=metadata,
                        body="\n".join(lines[closing_index + 1 :]),
                        has_frontmatter=True,
                        error=f"list item follows scalar field '{current_key}'",
                        error_line=line_number,
                        body_start_line=closing_index + 2,
                    )
                previous.append(parsed)
            # Other nested YAML is accepted but intentionally not interpreted.
            continue

        match = re.match(r"^([A-Za-z_][A-Za-z0-9_.-]*):(?:\s*(.*))?$", line)
        if not match:
            return FrontMatter(
                metadata=metadata,
                body="\n".join(lines[closing_index + 1 :]),
                has_frontmatter=True,
                error="expected a top-level 'key: value' field",
                error_line=line_number,
                body_start_line=closing_index + 2,
            )
        key, raw_value = match.group(1), match.group(2) or ""
        if key in metadata:
            return FrontMatter(
                metadata=metadata,
                body="\n".join(lines[closing_index + 1 :]),
                has_frontmatter=True,
                error=f"duplicate YAML field '{key}'",
                error_line=line_number,
                body_start_line=closing_index + 2,
            )
        parsed, error = _parse_scalar(raw_value)
        if error:
            return FrontMatter(
                metadata=metadata,
                body="\n".join(lines[closing_index + 1 :]),
                has_frontmatter=True,
                error=error,
                error_line=line_number,
                body_start_line=closing_index + 2,
            )
        metadata[key] = parsed
        current_key = key

    return FrontMatter(
        metadata=metadata,
        body="\n".join(lines[closing_index + 1 :]),
        has_frontmatter=True,
        body_start_line=closing_index + 2,
    )


def _corpus_markdown_files(root: Path) -> list[Path]:
    files: list[Path] = []
    for directory_name in CORPUS_DIRECTORIES:
        directory = root / directory_name
        if not directory.is_dir():
            continue
        for path in directory.rglob("*.md"):
            if path.is_file() and path.name not in EXCLUDED_CORPUS_NAMES:
                files.append(path)
    return sorted(files, key=lambda path: path.relative_to(root).as_posix().casefold())


def _workspace_markdown_files(root: Path) -> list[Path]:
    files = [
        path
        for path in root.rglob("*.md")
        if path.is_file() and ".git" not in path.relative_to(root).parts
    ]
    return sorted(files, key=lambda path: path.relative_to(root).as_posix().casefold())


def _metadata_text(metadata: dict[str, Any], *keys: str) -> str:
    for key in keys:
        value = metadata.get(key)
        if isinstance(value, str) and _is_meaningful(value):
            return value.strip()
    return ""


def _first_h1(body: str) -> str:
    in_fence = False
    for line in body.splitlines():
        if re.match(r"^\s*(```|~~~)", line):
            in_fence = not in_fence
            continue
        if in_fence:
            continue
        match = re.match(r"^#\s+(.+?)\s*#*\s*$", line)
        if match:
            return match.group(1).strip()
    return ""


def _clean_inline_markdown(text: str) -> str:
    text = re.sub(r"!\[([^]]*)\]\([^)]*\)", r"\1", text)
    text = re.sub(r"\[([^]]+)\]\([^)]*\)", r"\1", text)
    text = re.sub(r"`([^`]*)`", r"\1", text)
    text = re.sub(r"[*_~]+", "", text)
    return re.sub(r"\s+", " ", text).strip()


def _first_summary(body: str, limit: int = 220) -> str:
    paragraph: list[str] = []
    in_fence = False
    in_comment = False

    for raw_line in body.splitlines():
        line = raw_line.strip()
        if "<!--" in line:
            in_comment = True
        if in_comment:
            if "-->" in line:
                in_comment = False
            continue
        if re.match(r"^(```|~~~)", line):
            in_fence = not in_fence
            continue
        if in_fence:
            continue
        if not line:
            if paragraph:
                break
            continue
        if re.match(r"^#{1,6}\s+", line) or re.match(r"^([-*_])\1{2,}$", line):
            if paragraph:
                break
            continue
        if re.match(r"^(?:[-+*]|\d+[.)])\s+", line) or line.startswith("|"):
            if paragraph:
                break
            continue
        if line.startswith(">"):
            line = line.lstrip("> ").strip()
            if re.match(r"^\[![A-Za-z]+\]$", line):
                continue
        if not line:
            continue
        paragraph.append(line)

    summary = _clean_inline_markdown(" ".join(paragraph))
    if len(summary) <= limit:
        return summary
    shortened = summary[: limit + 1].rsplit(" ", 1)[0].rstrip()
    return (shortened or summary[:limit]).rstrip() + "…"


def _document_area_and_type(relative: Path, metadata: dict[str, Any]) -> tuple[str, str]:
    parts = relative.parts
    explicit_type = _metadata_text(metadata, "type")
    if parts[0] == "Brain":
        area = "Brain"
        if explicit_type:
            document_type = explicit_type
        elif len(parts) > 2:
            document_type = parts[1]
        else:
            document_type = "context"
    else:
        project_name = parts[1] if len(parts) > 2 else "General"
        area = f"Project: {project_name}"
        if explicit_type:
            document_type = explicit_type
        else:
            inferred = relative.stem.casefold()
            document_type = {
                "context": "context",
                "decisions": "decisions",
                "status": "status",
                "action-items": "actions",
            }.get(inferred, "documents")
    return area, document_type.replace("_", " ").replace("-", " ").strip().title()


def _markdown_destination(relative_path: str) -> str:
    from urllib.parse import quote

    return quote(relative_path, safe="/@:+-._~")


def _escape_link_label(label: str) -> str:
    return label.replace("\\", "\\\\").replace("]", "\\]")


def build_index(root: Path) -> str:
    """Build deterministic INDEX.md content without writing it."""
    root = root.resolve()
    entries: list[IndexEntry] = []
    for path in _corpus_markdown_files(root):
        text = read_utf8(path)
        frontmatter = parse_frontmatter(text)
        relative = path.relative_to(root)
        metadata = frontmatter.metadata if frontmatter.error is None else {}
        body = frontmatter.body if frontmatter.has_frontmatter else text
        title = _metadata_text(metadata, "title", "topic") or _first_h1(body) or path.stem
        area, document_type = _document_area_and_type(relative, metadata)
        entries.append(
            IndexEntry(
                area=area,
                document_type=document_type,
                title=title,
                status=_metadata_text(metadata, "status"),
                summary=_first_summary(body),
                relative_path=Path(
                    os.path.relpath(path, start=root / BRAIN_DIRECTORY)
                ).as_posix(),
            )
        )

    grouped: dict[str, dict[str, list[IndexEntry]]] = defaultdict(lambda: defaultdict(list))
    for entry in entries:
        grouped[entry.area][entry.document_type].append(entry)

    def area_key(area: str) -> tuple[int, str]:
        return (0 if area == "Brain" else 1, area.casefold())

    lines = [
        "# Brain Index",
        "",
        GENERATED_MARKER,
        "",
        "This file is generated deterministically from `Brain/` and `Projects/`.",
    ]
    if not entries:
        lines.extend(["", "_No Markdown documents found._"])
    else:
        for area in sorted(grouped, key=area_key):
            lines.extend(["", f"## {area}"])
            for document_type in sorted(grouped[area], key=str.casefold):
                lines.extend(["", f"### {document_type}"])
                sorted_entries = sorted(
                    grouped[area][document_type],
                    key=lambda entry: (entry.title.casefold(), entry.relative_path.casefold()),
                )
                for entry in sorted_entries:
                    destination = _markdown_destination(entry.relative_path)
                    item = f"- [{_escape_link_label(entry.title)}]({destination})"
                    if entry.status:
                        safe_status = _clean_inline_markdown(entry.status).replace("`", "'")
                        item += f" — status: `{safe_status}`"
                    if entry.summary:
                        item += f" — {entry.summary}"
                    lines.append(item)
    return "\n".join(lines) + "\n"


def update_index(root: Path, check: bool = False) -> int:
    expected = build_index(root)
    index_path = root / BRAIN_DIRECTORY / INDEX_NAME
    if check:
        try:
            current = read_utf8(index_path)
        except FileNotFoundError:
            print(f"ERROR: {BRAIN_DIRECTORY}/{INDEX_NAME} is missing", file=sys.stderr)
            return 1
        if current != expected:
            print(
                f"ERROR: {BRAIN_DIRECTORY}/{INDEX_NAME} is stale; "
                "run 'python Tools/brain.py index'",
                file=sys.stderr,
            )
            return 1
        print(f"OK: {BRAIN_DIRECTORY}/{INDEX_NAME} is up to date")
        return 0

    index_path.write_text(expected, encoding="utf-8", newline="\n")
    print(
        f"Wrote {BRAIN_DIRECTORY}/{INDEX_NAME} "
        f"({len(_corpus_markdown_files(root))} documents)"
    )
    return 0


def _relative_display(path: Path, root: Path) -> str:
    try:
        return path.resolve().relative_to(root.resolve()).as_posix()
    except (OSError, ValueError):
        return path.as_posix()


def _markdown_link_destinations(text: str) -> Iterable[tuple[int, str]]:
    inline_pattern = re.compile(
        r"!?\[[^\]\n]*\]\(\s*(<[^>]+>|[^\s)]+)(?:\s+['\"][^)]*['\"])?\s*\)"
    )
    reference_pattern = re.compile(r"^\s*\[[^\]]+\]:\s*(<[^>]+>|\S+)")
    in_fence = False
    fence_marker = ""
    for line_number, raw_line in enumerate(text.splitlines(), start=1):
        fence = re.match(r"^\s*(```|~~~)", raw_line)
        if fence:
            marker = fence.group(1)
            if not in_fence:
                in_fence = True
                fence_marker = marker
            elif marker == fence_marker:
                in_fence = False
            continue
        if in_fence:
            continue
        line = re.sub(r"`[^`]*`", "", raw_line)
        for match in inline_pattern.finditer(line):
            yield line_number, match.group(1)
        reference = reference_pattern.match(line)
        if reference:
            yield line_number, reference.group(1)


def _relative_link_target(source: Path, destination: str) -> Path | None:
    destination = destination.strip()
    if destination.startswith("<") and destination.endswith(">"):
        destination = destination[1:-1].strip()
    if not destination or destination.startswith("#"):
        return None
    if re.match(r"^[A-Za-z]:[\\/]", destination):
        return None
    split = urlsplit(destination)
    if split.scheme or split.netloc or destination.startswith(("/", "\\")):
        return None
    path_part = unquote(split.path)
    if not path_part:
        return None
    path_part = path_part.replace("/", os.sep)
    return (source.parent / path_part).resolve()


def _is_meaningful(value: Any) -> bool:
    if value is None or value is False:
        return False
    if isinstance(value, (list, tuple, set)):
        return any(_is_meaningful(item) for item in value)
    if isinstance(value, dict):
        return any(_is_meaningful(item) for item in value.values())
    text = str(value).strip().strip('"\'').strip()
    if text.casefold() in EMPTY_VALUES:
        return False
    if re.fullmatch(r"Y{4}(?:-M{2}(?:-D{2})?)?(?:T.*)?", text, flags=re.IGNORECASE):
        return False
    if text.startswith("*") and text.endswith("*"):
        return False
    return bool(text)


def _has_any_metadata(metadata: dict[str, Any], keys: Sequence[str]) -> bool:
    return any(_is_meaningful(metadata.get(key)) for key in keys)


def _section_has_content(body: str, names: Sequence[str]) -> bool:
    wanted = {name.casefold() for name in names}
    lines = body.splitlines()
    for index, line in enumerate(lines):
        match = re.match(r"^#{2,6}\s+(.+?)\s*#*\s*$", line.strip())
        if not match or match.group(1).strip().casefold() not in wanted:
            continue
        content: list[str] = []
        for candidate in lines[index + 1 :]:
            if re.match(r"^#{1,6}\s+", candidate.strip()):
                break
            stripped = candidate.strip()
            if stripped and not stripped.startswith("<!--"):
                content.append(stripped)
        meaningful_content = [
            item for item in content if _is_meaningful(item.lstrip("-+ ").strip())
        ]
        cleaned = _clean_inline_markdown(" ".join(meaningful_content)).strip("-* _")
        return _is_meaningful(cleaned)
    return False


def _source_record_has_locator(metadata: dict[str, Any], body: str) -> bool:
    locator_fields = (
        "raw_locator",
        "raw_path",
        "source",
        "source_link",
        "source_url",
        "original_url",
        "url",
        "url_or_path",
        "locator",
        "raw_materials",
    )
    if _has_any_metadata(metadata, locator_fields):
        return True
    for _, destination in _markdown_link_destinations(body):
        if "raw" in unquote(destination).casefold() or urlsplit(destination.strip("<> ")).scheme:
            return True
    return bool(re.search(r"https?://\S+", body))


def _decision_definitions(frontmatter: FrontMatter) -> list[tuple[str, int]]:
    definitions: list[tuple[str, int]] = []
    identifier = frontmatter.metadata.get("id")
    if isinstance(identifier, str) and re.fullmatch(r"[A-Za-z][A-Za-z0-9_-]*-\d+", identifier.strip()):
        definitions.append((identifier.strip().upper(), 2))
        return definitions

    heading_pattern = re.compile(r"^#{1,6}\s+([A-Z][A-Z0-9_-]*-\d{2,})\b")
    for offset, line in enumerate(frontmatter.body.splitlines(), start=frontmatter.body_start_line):
        match = heading_pattern.match(line.strip())
        if match:
            definitions.append((match.group(1).upper(), offset))
    return definitions


def _raw_entries(root: Path) -> list[Path]:
    raw_directory = root / BRAIN_DIRECTORY / "Sources" / "Raw"
    if not raw_directory.is_dir():
        return []
    return sorted(
        (path for path in raw_directory.rglob("*") if path.is_file() and path.name != ".gitkeep"),
        key=lambda path: path.relative_to(root).as_posix().casefold(),
    )


def _raw_manifests(root: Path) -> list[Path]:
    return [path for path in _raw_entries(root) if path.suffix.casefold() == ".md"]


def _raw_artifacts(root: Path) -> list[Path]:
    return [path for path in _raw_entries(root) if path.suffix.casefold() != ".md"]


def _metadata_strings(value: Any) -> list[str]:
    if isinstance(value, str):
        return [value.strip()] if _is_meaningful(value) else []
    if isinstance(value, list):
        return [item.strip() for item in value if isinstance(item, str) and _is_meaningful(item)]
    return []


def _resolve_artifact_path(root: Path, manifest: Path, value: str) -> tuple[Path | None, str | None]:
    normalized = unquote(value.strip()).replace("\\", "/")
    split = urlsplit(normalized)
    if split.scheme or split.netloc or normalized.startswith("/") or re.match(r"^[A-Za-z]:/", normalized):
        return None, "artifact_path must be relative to the workspace or manifest"

    if normalized == BRAIN_DIRECTORY or normalized.startswith(f"{BRAIN_DIRECTORY}/"):
        candidate = root / Path(normalized)
    elif normalized == "Sources" or normalized.startswith("Sources/"):
        candidate = root / BRAIN_DIRECTORY / Path(normalized)
    else:
        candidate = manifest.parent / Path(normalized)
    target = candidate.resolve()
    raw_directory = (root / BRAIN_DIRECTORY / "Sources" / "Raw").resolve()
    try:
        target.relative_to(raw_directory)
    except ValueError:
        return None, "artifact_path points outside Brain/Sources/Raw"
    if target.suffix.casefold() == ".md":
        return None, "artifact_path must reference a non-Markdown artifact"
    return target, None


def lint_workspace(root: Path) -> list[LintIssue]:
    """Return deterministic lint findings without changing the workspace."""
    root = root.resolve()
    issues: list[LintIssue] = []
    parsed_files: dict[Path, FrontMatter] = {}
    decision_locations: dict[str, list[tuple[Path, int]]] = defaultdict(list)

    for path in _workspace_markdown_files(root):
        try:
            text = read_utf8(path)
        except (OSError, UnicodeError) as error:
            issues.append(LintIssue("ERROR", path, 1, f"cannot read UTF-8 text: {error}"))
            continue
        frontmatter = parse_frontmatter(text)
        parsed_files[path.resolve()] = frontmatter
        if frontmatter.error:
            issues.append(
                LintIssue(
                    "ERROR",
                    path,
                    frontmatter.error_line or 1,
                    f"malformed frontmatter: {frontmatter.error}",
                )
            )

        for line_number, destination in _markdown_link_destinations(text):
            try:
                target = _relative_link_target(path, destination)
            except ValueError:
                issues.append(LintIssue("ERROR", path, line_number, f"malformed link destination: {destination}"))
                continue
            if target is not None and not target.exists():
                issues.append(
                    LintIssue("ERROR", path, line_number, f"broken relative link: {destination.strip('<>')}")
                )

        relative = path.relative_to(root)
        parts = relative.parts
        in_corpus = bool(parts) and parts[0] in CORPUS_DIRECTORIES
        if in_corpus:
            for identifier, line_number in _decision_definitions(frontmatter):
                decision_locations[identifier].append((path, line_number))

        metadata = frontmatter.metadata
        body = frontmatter.body if frontmatter.has_frontmatter else text
        is_knowledge = in_corpus and (
            (len(parts) >= 2 and parts[0] == "Brain" and parts[1] == "Knowledge")
            or str(metadata.get("type", "")).casefold() == "knowledge"
        )
        if is_knowledge:
            has_provenance = _has_any_metadata(metadata, ("provenance", "sources")) or _section_has_content(
                body,
                (
                    "Provenance",
                    "Sources",
                    "\u041f\u0440\u043e\u0438\u0441\u0445\u043e\u0436\u0434\u0435\u043d\u0438\u0435",
                    "\u0418\u0441\u0442\u043e\u0447\u043d\u0438\u043a\u0438",
                ),
            )
            if not has_provenance:
                issues.append(
                    LintIssue("WARN", path, 1, "knowledge note has empty provenance/sources")
                )

        in_sources = len(parts) >= 2 and parts[0] == "Brain" and parts[1] == "Sources"
        in_raw = in_sources and len(parts) >= 3 and parts[2] == "Raw"
        is_source_record = in_sources and not in_raw and (
            path.suffix.casefold() == ".md" or str(metadata.get("type", "")).casefold() in {"source", "source-record"}
        )
        if is_source_record and not _source_record_has_locator(metadata, body):
            issues.append(
                LintIssue("WARN", path, 1, "source record has no raw locator or source link")
            )

    for identifier, locations in sorted(decision_locations.items()):
        if len(locations) < 2:
            continue
        location_text = ", ".join(
            f"{_relative_display(path, root)}:{line}" for path, line in locations
        )
        first_path, first_line = locations[0]
        issues.append(
            LintIssue("ERROR", first_path, first_line, f"duplicate decision ID {identifier}: {location_text}")
        )

    locator_fields = ("source_url", "original_url", "url", "url_or_path", "source", "source_path")
    retrieval_fields = (
        "retrieved_at",
        "retrieved",
        "captured_at",
        "captured",
        "ingested",
        "downloaded_at",
        "date",
    )
    referenced_artifacts: dict[Path, list[Path]] = defaultdict(list)
    for manifest in _raw_manifests(root):
        frontmatter = parsed_files.get(manifest.resolve())
        if frontmatter is None:
            # Raw Markdown manifests are part of the Markdown scan, but retain a
            # defensive fallback for callers with unusual filesystem races.
            try:
                frontmatter = parse_frontmatter(read_utf8(manifest))
            except (OSError, UnicodeError) as error:
                issues.append(LintIssue("ERROR", manifest, 1, f"cannot read raw manifest: {error}"))
                continue

        missing: list[str] = []
        if not frontmatter.has_frontmatter:
            missing.extend(["source locator", "retrieval date"])
        else:
            if not _has_any_metadata(frontmatter.metadata, locator_fields):
                missing.append("source locator")
            if not _has_any_metadata(frontmatter.metadata, retrieval_fields):
                missing.append("retrieval date")
        if missing:
            issues.append(
                LintIssue("ERROR", manifest, 1, f"raw manifest missing required provenance: {', '.join(missing)}")
            )

        artifact_value = frontmatter.metadata.get("artifact_path")
        artifact_paths = _metadata_strings(artifact_value)
        if _is_meaningful(artifact_value) and not artifact_paths:
            issues.append(
                LintIssue("ERROR", manifest, 1, "artifact_path must be a string or list of strings")
            )
        for declared_path in artifact_paths:
            target, path_error = _resolve_artifact_path(root, manifest, declared_path)
            if path_error:
                issues.append(LintIssue("ERROR", manifest, 1, path_error))
                continue
            assert target is not None
            if not target.is_file():
                issues.append(
                    LintIssue("ERROR", manifest, 1, f"artifact_path does not exist: {declared_path}")
                )
                continue
            referenced_artifacts[target].append(manifest)
            if not _is_meaningful(frontmatter.metadata.get("content_hash")):
                issues.append(
                    LintIssue("WARN", manifest, 1, f"artifact has no content_hash: {declared_path}")
                )

    for artifact in _raw_artifacts(root):
        if artifact.resolve() not in referenced_artifacts:
            issues.append(
                LintIssue("ERROR", artifact, 1, "raw artifact has no Markdown manifest with artifact_path")
            )

    severity_order = {"ERROR": 0, "WARN": 1}
    return sorted(
        issues,
        key=lambda issue: (
            severity_order.get(issue.severity, 9),
            _relative_display(issue.path, root).casefold(),
            issue.line,
            issue.message.casefold(),
        ),
    )


def print_lint(root: Path) -> int:
    issues = lint_workspace(root)
    for issue in issues:
        print(
            f"{issue.severity} {_relative_display(issue.path, root)}:{issue.line} {issue.message}"
        )
    errors = sum(issue.severity == "ERROR" for issue in issues)
    warnings = sum(issue.severity == "WARN" for issue in issues)
    print(f"Lint: {errors} error(s), {warnings} warning(s)")
    return 1 if errors else 0


def _markdown_count(directory: Path) -> int:
    if not directory.is_dir():
        return 0
    return sum(1 for path in directory.rglob("*.md") if path.is_file())


def status_lines(root: Path) -> list[str]:
    brain = root / "Brain"
    capture_statuses: Counter[str] = Counter()
    inbox = brain / "Inbox"
    if inbox.is_dir():
        for path in sorted(inbox.rglob("*.md")):
            if not path.is_file():
                continue
            try:
                frontmatter = parse_frontmatter(read_utf8(path))
                status = _metadata_text(frontmatter.metadata, "status").casefold() or "unknown"
            except (OSError, UnicodeError):
                status = "unreadable"
            capture_statuses[status] += 1

    active_sessions = 0
    sessions = brain / "Sessions"
    if sessions.is_dir():
        for path in sessions.rglob("*.md"):
            if not path.is_file():
                continue
            try:
                status = _metadata_text(parse_frontmatter(read_utf8(path)).metadata, "status").casefold()
            except (OSError, UnicodeError):
                continue
            if status in ACTIVE_SESSION_STATUSES:
                active_sessions += 1

    capture_total = sum(capture_statuses.values())
    status_text = ", ".join(f"{key}={capture_statuses[key]}" for key in sorted(capture_statuses)) or "none"
    sources = brain / "Sources"
    raw_manifest_count = len(_raw_manifests(root))
    raw_artifact_count = len(_raw_artifacts(root))
    source_records = 0
    if sources.is_dir():
        raw_directory = (sources / "Raw").resolve()
        for path in sources.rglob("*.md"):
            if path.is_file() and raw_directory not in path.resolve().parents:
                source_records += 1
    projects_directory = root / "Projects"
    project_count = (
        sum(1 for path in projects_directory.iterdir() if path.is_dir() and not path.name.startswith("."))
        if projects_directory.is_dir()
        else 0
    )
    return [
        f"Captures: {capture_total} ({status_text})",
        f"Active sessions: {active_sessions}",
        f"Sources: raw_manifests={raw_manifest_count}, raw_artifacts={raw_artifact_count}, records={source_records}",
        f"Knowledge: {_markdown_count(brain / 'Knowledge')}",
        f"Projects: {project_count}",
    ]


def _single_line(value: str) -> str:
    return re.sub(r"\s+", " ", value).strip()


def _normalize_log_path(raw_path: str, root: Path) -> str:
    value = _single_line(raw_path).replace("\\", "/")
    if not value:
        raise ValueError("log file path must not be empty")
    if re.match(r"^[A-Za-z]:/", value) and os.name != "nt":
        raise ValueError(f"log file path is outside workspace: {raw_path}")

    root = root.resolve()
    supplied = Path(value).expanduser()
    candidate = supplied.resolve() if supplied.is_absolute() else (root / supplied).resolve()
    try:
        return candidate.relative_to(root).as_posix()
    except ValueError as error:
        raise ValueError(f"log file path is outside workspace: {raw_path}") from error


def append_log(
    root: Path,
    operation: str,
    title: str,
    files: Sequence[str] | None = None,
    note: str | None = None,
    today: date | None = None,
) -> None:
    operation = _single_line(operation)
    title = _single_line(title)
    normalized_note = _single_line(note) if note is not None else ""
    if not operation:
        raise ValueError("operation must not be empty")
    if not title:
        raise ValueError("title must not be empty")
    if len(operation) > MAX_OPERATION_LENGTH:
        raise ValueError(f"operation exceeds {MAX_OPERATION_LENGTH} characters")
    if len(title) > MAX_TITLE_LENGTH:
        raise ValueError(f"title exceeds {MAX_TITLE_LENGTH} characters")
    if len(normalized_note) > MAX_NOTE_LENGTH:
        raise ValueError(f"note exceeds {MAX_NOTE_LENGTH} characters")

    normalized_files = [_normalize_log_path(item, root) for item in (files or []) if _single_line(item)]
    lines = [f"## [{(today or date.today()).isoformat()}] {operation} | {title}"]
    if normalized_files:
        lines.extend(["", "Files:"])
        lines.extend(f"- `{item}`" for item in normalized_files)
    if normalized_note:
        lines.extend(["", f"Note: {normalized_note}"])
    entry = "\n".join(lines) + "\n"

    log_path = root / BRAIN_DIRECTORY / LOG_NAME
    log_path.parent.mkdir(parents=True, exist_ok=True)
    needs_separator = log_path.exists() and log_path.stat().st_size > 0
    with log_path.open("a", encoding="utf-8", newline="\n") as handle:
        if needs_separator:
            handle.write("\n")
        handle.write(entry)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="brain.py",
        description="Dependency-free automation for the Markdown Brain workspace.",
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    index_parser = subparsers.add_parser("index", help="generate deterministic INDEX.md")
    index_parser.add_argument("--check", action="store_true", help="fail if INDEX.md is missing or stale")

    subparsers.add_parser("lint", help="run read-only workspace checks")
    subparsers.add_parser("status", help="show compact workspace counts")

    log_parser = subparsers.add_parser("log", help="append a metadata-only LOG.md entry")
    log_parser.add_argument("--operation", required=True, help="operation type")
    log_parser.add_argument("--title", required=True, help="entry title")
    log_parser.add_argument("--file", dest="files", nargs="+", action="extend", default=[], help="affected path(s)")
    log_parser.add_argument("--note", help="short note")
    return parser


def main(argv: Sequence[str] | None = None, root: Path | None = None) -> int:
    parser = build_parser()
    arguments = parser.parse_args(argv)
    actual_root = (root or workspace_root()).resolve()
    try:
        if arguments.command == "index":
            return update_index(actual_root, check=arguments.check)
        if arguments.command == "lint":
            return print_lint(actual_root)
        if arguments.command == "status":
            print("\n".join(status_lines(actual_root)))
            return 0
        if arguments.command == "log":
            append_log(
                actual_root,
                operation=arguments.operation,
                title=arguments.title,
                files=arguments.files,
                note=arguments.note,
            )
            print(f"Appended {BRAIN_DIRECTORY}/{LOG_NAME}")
            return 0
    except (OSError, UnicodeError, ValueError) as error:
        print(f"ERROR: {error}", file=sys.stderr)
        return 2
    parser.error(f"unknown command: {arguments.command}")
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
